version: '3'
services: 
  user:
    build:
      context: ./User-Node
      dockerfile: Dockerfile
    env_file: .env
    image: user-node_web
    ports: 
      - "5000:5000"
    depends_on:
      - user_db
    environment:
      - MONGO_URI=$MONGO_URL
  user_db: 
    image: mongo
    volumes:
      - mongo-data:/data/db
  post:
    build:
      context: ./Post-Django
      dockerfile: Dockerfile 
volumes:
  mongo-data: 