version: '3'
services: 
  user:
    build:
      context: ./User-Node
      dockerfile: Dockerfile
    env_file: ./User-Node/.env
    image: clonerops/user-services
    ports: 
      - "5000:5000"
    depends_on:
      - user_db
    environment:
      - MONGO_URI=$MONGO_URL
  user_db: 
    image: mongo
    volumes:
      - mongo-data:/data/db
  post:
    build:
      context: ./Post-Django
      dockerfile: Dockerfile 
    command: python /app/manage.py runserver 0.0.0.0:8000
    image: clonerops/post-services
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    
volumes:
  mongo-data: 